apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: guarded-pr-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
    - taskSpec:
        steps:
        - uses:
            path: tektoncd/catalog/task/git-clone/0.2/git-clone.yaml@HEAD
        - uses:
            path: jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@HEAD
            name: next-version
        - uses:
            # path inherited from previous step so can be omitted
            name: jx-variables
        - uses:
            name: build-make-build
        - uses:
            name: check-registry
        - uses:
            name: build-container-build
        - uses:
            name: promote-changelog
        - uses:
            name: promote-helm-release
        - uses:
            name: promote-jx-promote
